version: 0.2

phases:
  build:
    commands:
      - |
        set -e
        echo "=== DEPLOYMENT PHASE ==="
        
        # Get ECR repository URI
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        REPOSITORY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/image-services"
        
        # Find EC2 instance
        echo "Finding EC2 instance 'server'..."
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=server" "Name=instance-state-name,Values=running" \
          --region "${AWS_DEFAULT_REGION}" \
          --query 'Reservations[0].Instances[0].InstanceId' \
          --output text 2>/dev/null || echo "")
        
        if [ -z "${INSTANCE_ID}" ] || [ "${INSTANCE_ID}" = "None" ]; then
          echo "WARNING: No running 'server' instance found. Skipping deployment."
          exit 0
        fi
        
        echo "Found instance: ${INSTANCE_ID}"
        
        # Verify SSM Agent is online
        echo "Checking SSM Agent status..."
        MAX_RETRIES=10
        RETRY_COUNT=0
        SSM_ONLINE=false
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          SSM_STATUS=$(aws ssm describe-instance-information \
            --filters "Key=InstanceIds,Values=${INSTANCE_ID}" \
            --region "${AWS_DEFAULT_REGION}" \
            --query 'InstanceInformationList[0].PingStatus' \
            --output text 2>/dev/null || echo "Unknown")
          
          if [ "${SSM_STATUS}" = "Online" ]; then
            echo "✅ SSM Agent is online"
            SSM_ONLINE=true
            break
          fi
          
          RETRY_COUNT=$((RETRY_COUNT + 1))
          echo "SSM status: ${SSM_STATUS} (retry ${RETRY_COUNT}/${MAX_RETRIES})"
          [ $RETRY_COUNT -lt $MAX_RETRIES ] && sleep 5
        done
        
        if [ "${SSM_ONLINE}" != "true" ]; then
          echo "ERROR: SSM Agent not online after ${MAX_RETRIES} retries. Status: ${SSM_STATUS}"
          exit 1
        fi
        
        # Send deployment command
        echo "Sending deployment command via SSM..."
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "${INSTANCE_ID}" \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=[\"/opt/update-container.sh ${REPOSITORY_URI} server\"]" \
          --region "${AWS_DEFAULT_REGION}" \
          --query 'Command.CommandId' --output text 2>&1)
        
        if [ $? -ne 0 ]; then
          echo "ERROR: Failed to send SSM command: ${COMMAND_ID}"
          exit 1
        fi
        
        echo "Command ID: ${COMMAND_ID}"
        
        # Wait for completion
        echo "Waiting for deployment..."
        MAX_WAIT=120
        WAIT_COUNT=0
        STATUS="InProgress"
        
        while [ "${STATUS}" = "InProgress" ] && [ $WAIT_COUNT -lt $MAX_WAIT ]; do
          sleep 5
          WAIT_COUNT=$((WAIT_COUNT + 5))
          STATUS=$(aws ssm get-command-invocation \
            --command-id "${COMMAND_ID}" \
            --instance-id "${INSTANCE_ID}" \
            --region "${AWS_DEFAULT_REGION}" \
            --query 'Status' --output text 2>/dev/null || echo "InProgress")
          
          [ "${STATUS}" != "InProgress" ] && [ "${STATUS}" != "Pending" ] && break
          echo "Status: ${STATUS} (${WAIT_COUNT}s)"
        done
        
        # Get and display results
        OUTPUT=$(aws ssm get-command-invocation \
          --command-id "${COMMAND_ID}" \
          --instance-id "${INSTANCE_ID}" \
          --region "${AWS_DEFAULT_REGION}" \
          --query 'StandardOutputContent' --output text 2>/dev/null || echo "")
        
        ERROR=$(aws ssm get-command-invocation \
          --command-id "${COMMAND_ID}" \
          --instance-id "${INSTANCE_ID}" \
          --region "${AWS_DEFAULT_REGION}" \
          --query 'StandardErrorContent' --output text 2>/dev/null || echo "")
        
        [ -n "${OUTPUT}" ] && echo "=== Output ===" && echo "${OUTPUT}"
        [ -n "${ERROR}" ] && echo "=== Error ===" && echo "${ERROR}"
        
        if [ "${STATUS}" != "Success" ]; then
          echo "ERROR: Deployment failed. Status: ${STATUS}"
          exit 1
        fi
        
        echo "✅ Deployment completed successfully"

