version: 0.2

phases:
  install:
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Environment Amazon Linux 2023 (Custom Image)"
      - echo "Verifying tools..."
      - buildah --version
      - aws --version
      
      - echo "Configuring Buildah storage..."
      - mkdir -p /etc/containers
      - |
        cat > /etc/containers/storage.conf <<'STORAGE_EOF'
        [storage]
        driver = "vfs"
        runroot = "/var/run/containers/storage"
        graphroot = "/var/lib/containers/storage"
        STORAGE_EOF
      - mkdir -p /var/lib/containers/storage
      - mkdir -p /var/run/containers/storage
      - chmod 755 /var/lib/containers/storage
      - chmod 755 /var/run/containers/storage
      - echo "Buildah storage configured"

  pre_build:
    on-failure: ABORT
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Verifying CodeBuild environment (codebuild-buildah)..."
      - buildah --version
      - echo "CodeBuild environment verified"
      - echo "Logging in to Amazon ECR..."
      - |
        set -e
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        export AWS_ACCOUNT_ID
        ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
        export ECR_REGISTRY
        echo "ECR Registry: ${ECR_REGISTRY}"
      - |
        set -e
        aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | buildah login --username AWS --password-stdin "${ECR_REGISTRY}"
      - echo "ECR login successful"
      - |
        set -e
        REPOSITORY_URI="${ECR_REGISTRY}/image-services"
        BASE_IMAGE_URI="${ECR_REGISTRY}/image-base:base-image-node22"
        CODEBUILD_IMAGE_URI="${ECR_REGISTRY}/image-base:codebuild-buildah"
        export REPOSITORY_URI
        export BASE_IMAGE_URI
        export CODEBUILD_IMAGE_URI
        echo "Repository URI: ${REPOSITORY_URI}"
        echo "Base Image URI (for application): ${BASE_IMAGE_URI}"
        echo "CodeBuild Image URI (environment): ${CODEBUILD_IMAGE_URI}"
      - |
        set -e
        echo "Verifying CodeBuild image exists in ECR..."
        if ! aws ecr describe-images --repository-name image-base --image-ids imageTag=codebuild-buildah --region "${AWS_DEFAULT_REGION}" --query 'imageDetails[0].imageTags' --output text 2>/dev/null; then
          echo "WARNING: Could not verify codebuild-buildah image in ECR"
        fi
      - |
        #!/usr/bin/env bash
        set +e
        echo "Pulling base Node.js image (base-image-node22)..."
        echo "URI: ${BASE_IMAGE_URI}"
        
        if buildah pull "${BASE_IMAGE_URI}"; then
            echo "Base image pulled successfully (auto-detected platform)"
        else
            echo "WARNING: Failed to pull base image. Retrying with explicit ARM64 platform..."
            if buildah pull --platform linux/arm64 "${BASE_IMAGE_URI}"; then
                echo "Base image pulled successfully with --platform linux/arm64"
            else
                echo "ERROR: Failed to pull base image ${BASE_IMAGE_URI}"
                echo "Listing available images in ECR for debugging:"
                aws ecr list-images --repository-name image-base --region "${AWS_DEFAULT_REGION}"
                exit 1
            fi
        fi
        set -e
      - |
        set -e
        if [ -n "${CODEBUILD_RESOLVED_SOURCE_VERSION}" ]; then
          COMMIT_HASH=$(echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c 1-7)
        else
          COMMIT_HASH="latest"
        fi
        IMAGE_TAG="${COMMIT_HASH}"
        export IMAGE_TAG
        echo "Image tag: ${IMAGE_TAG}"

  build:
    on-failure: ABORT
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Building application image using"
      - echo "1. CodeBuild environment codebuild-buildah from ECR image-base"
      - echo "2. Base image base-image-node22 from ECR image-base"
      - echo "3. Application code from CodePipeline source zip"
      - echo "4. Target repository image-services ECR"
      - |
        set -e
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        export AWS_ACCOUNT_ID
        ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
        export ECR_REGISTRY
        REPOSITORY_URI="${ECR_REGISTRY}/image-services"
        BASE_IMAGE_URI="${ECR_REGISTRY}/image-base:base-image-node22"
        export REPOSITORY_URI
        export BASE_IMAGE_URI
        
        if [ -n "${CODEBUILD_RESOLVED_SOURCE_VERSION}" ]; then
          COMMIT_HASH=$(echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c 1-7)
        else
          COMMIT_HASH="latest"
        fi
        IMAGE_TAG="${COMMIT_HASH}"
        export IMAGE_TAG
        
        echo "Building container image for ARM64..."
        echo "Base image: ${BASE_IMAGE_URI}"
        echo "Repository: ${REPOSITORY_URI}"
        echo "Tags: server, latest, ${IMAGE_TAG}"
        echo "Application code location: ./code"
      - |
        set -e
        echo "Building image with buildah for ARM64..."
        echo "Using base-image-node22 and application code from ./code"
        echo "Base image: ${BASE_IMAGE_URI}"
        echo "Target image: ${REPOSITORY_URI}:server"
        echo "Dockerfile location: ./code/Dockerfile"
        echo "Build context: ./code"
        
        # Verify Dockerfile exists
        if [ ! -f ./code/Dockerfile ]; then
          echo "ERROR: Dockerfile not found at ./code/Dockerfile"
          exit 1
        fi
        
        # Build the image
        buildah bud --platform linux/arm64 --isolation oci \
          --build-arg BASE_IMAGE="${BASE_IMAGE_URI}" \
          -t "${REPOSITORY_URI}:server" \
          -f ./code/Dockerfile ./code
        
        echo "✅ Build completed successfully"
      - |
        set -e
        echo "Creating additional tags..."
        buildah tag "${REPOSITORY_URI}:server" "${REPOSITORY_URI}:latest"
        buildah tag "${REPOSITORY_URI}:server" "${REPOSITORY_URI}:${IMAGE_TAG}"
      - |
        set -e
        echo "Built images:"
        if ! buildah images | grep -q "${REPOSITORY_URI}"; then
          echo "ERROR: No images found for ${REPOSITORY_URI}"
          echo "Available images:"
          buildah images
          exit 1
        else
          buildah images | grep "${REPOSITORY_URI}"
          echo "✅ Image built successfully: ${REPOSITORY_URI}:server"
        fi

  post_build:
    on-failure: ABORT
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - |
        set -e
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        export AWS_ACCOUNT_ID
        ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
        export ECR_REGISTRY
        REPOSITORY_URI="${ECR_REGISTRY}/image-services"
        export REPOSITORY_URI
        
        if [ -n "${CODEBUILD_RESOLVED_SOURCE_VERSION}" ]; then
          COMMIT_HASH=$(echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c 1-7)
        else
          COMMIT_HASH="latest"
        fi
        IMAGE_TAG="${COMMIT_HASH}"
        export IMAGE_TAG
        
        echo "Pushing images to ECR..."
      - |
        set -e
        echo "Pushing server tag..."
        buildah push "${REPOSITORY_URI}:server"
      - |
        set -e
        echo "Pushing latest tag..."
        buildah push "${REPOSITORY_URI}:latest"
      - |
        set -e
        echo "Pushing commit hash tag: ${IMAGE_TAG}"
        buildah push "${REPOSITORY_URI}:${IMAGE_TAG}"

