version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | buildah login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/node-backend-app
      - BASE_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/node-backend-base:base-image-node22
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image with Buildah...
      - buildah bud --build-arg BASE_IMAGE=$BASE_IMAGE_URI -t $REPOSITORY_URI:latest -f ./code/Dockerfile ./code
      - buildah tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the image with Buildah...
      - buildah push $REPOSITORY_URI:latest
      - buildah push $REPOSITORY_URI:$IMAGE_TAG
      - echo Launching EC2 instance...
      - AMI_ID=$(aws ssm get-parameters --names /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64 --region $AWS_DEFAULT_REGION --query 'Parameters[0].Value' --output text)
      - echo "Using VPC created by Terraform..."
      - VPC_ID=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=eks-vpc" --region $AWS_DEFAULT_REGION --query 'Vpcs[0].VpcId' --output text)
      - echo "VPC ID - $VPC_ID"
      - |
        if [ "$VPC_ID" == "None" ] || [ -z "$VPC_ID" ]; then
          echo "ERROR: VPC not found!"
          exit 1
        fi
      - echo "Getting first available subnet..."
      - echo "Listing all subnets in VPC..."
      - aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --region $AWS_DEFAULT_REGION --query 'Subnets[*].[SubnetId,AvailabilityZone]' --output table
      - SUBNET_ID=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --region $AWS_DEFAULT_REGION --query 'Subnets[0].SubnetId' --output text)
      - echo "Subnet ID - $SUBNET_ID"
      - |
        if [ "$SUBNET_ID" == "None" ] || [ -z "$SUBNET_ID" ]; then
          echo "ERROR: No subnets found in VPC!"
          exit 1
        fi
      - echo "Creating security group..."
      - SG_ID=$(aws ec2 create-security-group --group-name node-backend-app-sg-$(date +%s) --description "Security group for node backend app" --vpc-id $VPC_ID --region $AWS_DEFAULT_REGION --query 'GroupId' --output text)
      - echo "Security Group ID - $SG_ID"
      - echo "Adding ingress rules..."
      - aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 80 --cidr 0.0.0.0/0 --region $AWS_DEFAULT_REGION
      - aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 8080 --cidr 0.0.0.0/0 --region $AWS_DEFAULT_REGION
      - aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 22 --cidr 0.0.0.0/0 --region $AWS_DEFAULT_REGION
      - echo "Creating user data script..."
      - |
        cat > /tmp/user-data.sh << 'USERDATA'
        #!/bin/bash
        yum update -y
        yum install -y docker
        systemctl start docker
        systemctl enable docker
        usermod -a -G docker ec2-user
        
        # Get ECR login and pull image
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
        
        # Pull and run the container
        docker pull $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-backend-app:latest
        docker run -d -p 80:8080 -p 8080:8080 --name node-app $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-backend-app:latest
        USERDATA
      - echo "Launching EC2 instance..."
      - INSTANCE_ID=$(aws ec2 run-instances --image-id $AMI_ID --instance-type t3.micro --subnet-id $SUBNET_ID --security-group-ids $SG_ID --iam-instance-profile Name=node-backend-ec2-profile --associate-public-ip-address --user-data file:///tmp/user-data.sh --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=node-backend-app},{Key=ManagedBy,Value=CodeBuild}]' --region $AWS_DEFAULT_REGION --query 'Instances[0].InstanceId' --output text)
      - echo "Launched EC2 instance - $INSTANCE_ID"
      - PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --region $AWS_DEFAULT_REGION --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
      - echo "Instance Public IP - $PUBLIC_IP"
      - echo "Application will be available at http://$PUBLIC_IP:80 and http://$PUBLIC_IP:8080"
